import Head from "next/head";
import { promises as fs } from "fs";
import Header from "@/components/header";
import { useEffect, useState } from "react";
import Loading from "@/components/loading/loading";
import SandwichesList from "@/components/sandwichesList";

export async function getStaticProps() {
  const file = await fs.readFile(
    process.cwd() + "/src/data/recipes.json",
    "utf8"
  );
  const data = JSON.parse(file);
  return {
    props: {
      recipes: data,
    },
  };
}

export default function Home({ recipes }) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 4000);

    return () => clearTimeout(timer);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading ? (
        <Loading />
      ) : (
        <>
          <Header />
          <main className="mainContainer">
            <SandwichesList recipes={recipes} />
          </main>
        </>
      )}
    </>
  );
}
