import Header from "@/components/header";
import SandwichesList from "@/components/sandwichesList";
import Head from "next/head";
import { promises as fs } from "fs";

export async function getStaticProps() {
  const file = await fs.readFile(
    process.cwd() + "/src/data/recipes.json",
    "utf8"
  );
  const data = JSON.parse(file);
  return {
    props: {
      recipes: data,
    },
  };
}

export default function Home({ recipes }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="mainContainer">
        <SandwichesList recipes={recipes} />
      </main>
    </>
  );
}
